10 standaard google blocks uit blocks repo verwijderen
leaphy-robotics/leaphy-blocks pull request #34
Opened 2024-01-02 13:36 UTC by JeftadeGraaf

Icm #103 van leaphy-webbased. Heb de blokken verwijderd uit blocks.js

2024-01-18 07:15 UTC, koen1711 approved these changes

2024-01-19 14:31 UTC, rmoesbergen requested changes
Het idee klopt, maar in de praktijk breekt het dingen (styling van de blocks + js errors)

2024-01-21 07:47 UTC, koen1711 requested changes

2024-01-21 07:47 UTC, koen1711 commented on blocks/blocks.js
> -import * as loops from "./loops";
Er mist nu een loop

2024-01-21 20:34 UTC, JeftadeGraaf commented
yes, zie het nu ook. zal ermee bezig gaan, en van tevoren goed testen

2024-04-15 18:06 UTC, rmoesbergen commented
this has already been done in a different PR

2024-04-15 18:06 UTC, closed without merging